// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/blog.proto

/*
Package blogpb is a generated protocol buffer package.

It is generated from these files:
	proto/blog.proto

It has these top-level messages:
	Blog
	CreateBlogReq
	CreateBlogRes
	ReadBlogReq
	ReadBlogRes
	UpdateBlogReq
	UpdateBlogRes
	DeleteBlogReq
	DeleteBlogRes
	ListBlogsReq
	ListBlogsRes
*/
package blogpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blog struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	AuthorId string `protobuf:"bytes,2,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
	Title    string `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Content  string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
}

func (m *Blog) Reset()                    { *m = Blog{} }
func (m *Blog) String() string            { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()               {}
func (*Blog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Blog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Blog) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Blog) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Blog) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateBlogReq struct {
	Blog *Blog `protobuf:"bytes,1,opt,name=blog" json:"blog,omitempty"`
}

func (m *CreateBlogReq) Reset()                    { *m = CreateBlogReq{} }
func (m *CreateBlogReq) String() string            { return proto.CompactTextString(m) }
func (*CreateBlogReq) ProtoMessage()               {}
func (*CreateBlogReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateBlogReq) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type CreateBlogRes struct {
	Blog *Blog `protobuf:"bytes,1,opt,name=blog" json:"blog,omitempty"`
}

func (m *CreateBlogRes) Reset()                    { *m = CreateBlogRes{} }
func (m *CreateBlogRes) String() string            { return proto.CompactTextString(m) }
func (*CreateBlogRes) ProtoMessage()               {}
func (*CreateBlogRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateBlogRes) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type ReadBlogReq struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadBlogReq) Reset()                    { *m = ReadBlogReq{} }
func (m *ReadBlogReq) String() string            { return proto.CompactTextString(m) }
func (*ReadBlogReq) ProtoMessage()               {}
func (*ReadBlogReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadBlogReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadBlogRes struct {
	Blog *Blog `protobuf:"bytes,1,opt,name=blog" json:"blog,omitempty"`
}

func (m *ReadBlogRes) Reset()                    { *m = ReadBlogRes{} }
func (m *ReadBlogRes) String() string            { return proto.CompactTextString(m) }
func (*ReadBlogRes) ProtoMessage()               {}
func (*ReadBlogRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadBlogRes) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type UpdateBlogReq struct {
	Blog *Blog `protobuf:"bytes,1,opt,name=blog" json:"blog,omitempty"`
}

func (m *UpdateBlogReq) Reset()                    { *m = UpdateBlogReq{} }
func (m *UpdateBlogReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateBlogReq) ProtoMessage()               {}
func (*UpdateBlogReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateBlogReq) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type UpdateBlogRes struct {
	Blog *Blog `protobuf:"bytes,1,opt,name=blog" json:"blog,omitempty"`
}

func (m *UpdateBlogRes) Reset()                    { *m = UpdateBlogRes{} }
func (m *UpdateBlogRes) String() string            { return proto.CompactTextString(m) }
func (*UpdateBlogRes) ProtoMessage()               {}
func (*UpdateBlogRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateBlogRes) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

type DeleteBlogReq struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteBlogReq) Reset()                    { *m = DeleteBlogReq{} }
func (m *DeleteBlogReq) String() string            { return proto.CompactTextString(m) }
func (*DeleteBlogReq) ProtoMessage()               {}
func (*DeleteBlogReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteBlogReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteBlogRes struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeleteBlogRes) Reset()                    { *m = DeleteBlogRes{} }
func (m *DeleteBlogRes) String() string            { return proto.CompactTextString(m) }
func (*DeleteBlogRes) ProtoMessage()               {}
func (*DeleteBlogRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteBlogRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListBlogsReq struct {
}

func (m *ListBlogsReq) Reset()                    { *m = ListBlogsReq{} }
func (m *ListBlogsReq) String() string            { return proto.CompactTextString(m) }
func (*ListBlogsReq) ProtoMessage()               {}
func (*ListBlogsReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ListBlogsRes struct {
	Blog *Blog `protobuf:"bytes,1,opt,name=blog" json:"blog,omitempty"`
}

func (m *ListBlogsRes) Reset()                    { *m = ListBlogsRes{} }
func (m *ListBlogsRes) String() string            { return proto.CompactTextString(m) }
func (*ListBlogsRes) ProtoMessage()               {}
func (*ListBlogsRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ListBlogsRes) GetBlog() *Blog {
	if m != nil {
		return m.Blog
	}
	return nil
}

func init() {
	proto.RegisterType((*Blog)(nil), "blog.Blog")
	proto.RegisterType((*CreateBlogReq)(nil), "blog.CreateBlogReq")
	proto.RegisterType((*CreateBlogRes)(nil), "blog.CreateBlogRes")
	proto.RegisterType((*ReadBlogReq)(nil), "blog.ReadBlogReq")
	proto.RegisterType((*ReadBlogRes)(nil), "blog.ReadBlogRes")
	proto.RegisterType((*UpdateBlogReq)(nil), "blog.UpdateBlogReq")
	proto.RegisterType((*UpdateBlogRes)(nil), "blog.UpdateBlogRes")
	proto.RegisterType((*DeleteBlogReq)(nil), "blog.DeleteBlogReq")
	proto.RegisterType((*DeleteBlogRes)(nil), "blog.DeleteBlogRes")
	proto.RegisterType((*ListBlogsReq)(nil), "blog.ListBlogsReq")
	proto.RegisterType((*ListBlogsRes)(nil), "blog.ListBlogsRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BlogService service

type BlogServiceClient interface {
	CreateBlog(ctx context.Context, in *CreateBlogReq, opts ...grpc.CallOption) (*CreateBlogRes, error)
	ReadBlog(ctx context.Context, in *ReadBlogReq, opts ...grpc.CallOption) (*ReadBlogRes, error)
	UpdateBlog(ctx context.Context, in *UpdateBlogReq, opts ...grpc.CallOption) (*UpdateBlogRes, error)
	DeleteBlog(ctx context.Context, in *DeleteBlogReq, opts ...grpc.CallOption) (*DeleteBlogRes, error)
	ListBlogs(ctx context.Context, in *ListBlogsReq, opts ...grpc.CallOption) (BlogService_ListBlogsClient, error)
}

type blogServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlogServiceClient(cc *grpc.ClientConn) BlogServiceClient {
	return &blogServiceClient{cc}
}

func (c *blogServiceClient) CreateBlog(ctx context.Context, in *CreateBlogReq, opts ...grpc.CallOption) (*CreateBlogRes, error) {
	out := new(CreateBlogRes)
	err := grpc.Invoke(ctx, "/blog.BlogService/CreateBlog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ReadBlog(ctx context.Context, in *ReadBlogReq, opts ...grpc.CallOption) (*ReadBlogRes, error) {
	out := new(ReadBlogRes)
	err := grpc.Invoke(ctx, "/blog.BlogService/ReadBlog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) UpdateBlog(ctx context.Context, in *UpdateBlogReq, opts ...grpc.CallOption) (*UpdateBlogRes, error) {
	out := new(UpdateBlogRes)
	err := grpc.Invoke(ctx, "/blog.BlogService/UpdateBlog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) DeleteBlog(ctx context.Context, in *DeleteBlogReq, opts ...grpc.CallOption) (*DeleteBlogRes, error) {
	out := new(DeleteBlogRes)
	err := grpc.Invoke(ctx, "/blog.BlogService/DeleteBlog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServiceClient) ListBlogs(ctx context.Context, in *ListBlogsReq, opts ...grpc.CallOption) (BlogService_ListBlogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BlogService_serviceDesc.Streams[0], c.cc, "/blog.BlogService/ListBlogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &blogServiceListBlogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlogService_ListBlogsClient interface {
	Recv() (*ListBlogsRes, error)
	grpc.ClientStream
}

type blogServiceListBlogsClient struct {
	grpc.ClientStream
}

func (x *blogServiceListBlogsClient) Recv() (*ListBlogsRes, error) {
	m := new(ListBlogsRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for BlogService service

type BlogServiceServer interface {
	CreateBlog(context.Context, *CreateBlogReq) (*CreateBlogRes, error)
	ReadBlog(context.Context, *ReadBlogReq) (*ReadBlogRes, error)
	UpdateBlog(context.Context, *UpdateBlogReq) (*UpdateBlogRes, error)
	DeleteBlog(context.Context, *DeleteBlogReq) (*DeleteBlogRes, error)
	ListBlogs(*ListBlogsReq, BlogService_ListBlogsServer) error
}

func RegisterBlogServiceServer(s *grpc.Server, srv BlogServiceServer) {
	s.RegisterService(&_BlogService_serviceDesc, srv)
}

func _BlogService_CreateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBlogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).CreateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/CreateBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).CreateBlog(ctx, req.(*CreateBlogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ReadBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBlogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).ReadBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/ReadBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).ReadBlog(ctx, req.(*ReadBlogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_UpdateBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBlogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).UpdateBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/UpdateBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).UpdateBlog(ctx, req.(*UpdateBlogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_DeleteBlog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBlogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServiceServer).DeleteBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blog.BlogService/DeleteBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServiceServer).DeleteBlog(ctx, req.(*DeleteBlogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogService_ListBlogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListBlogsReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlogServiceServer).ListBlogs(m, &blogServiceListBlogsServer{stream})
}

type BlogService_ListBlogsServer interface {
	Send(*ListBlogsRes) error
	grpc.ServerStream
}

type blogServiceListBlogsServer struct {
	grpc.ServerStream
}

func (x *blogServiceListBlogsServer) Send(m *ListBlogsRes) error {
	return x.ServerStream.SendMsg(m)
}

var _BlogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blog.BlogService",
	HandlerType: (*BlogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBlog",
			Handler:    _BlogService_CreateBlog_Handler,
		},
		{
			MethodName: "ReadBlog",
			Handler:    _BlogService_ReadBlog_Handler,
		},
		{
			MethodName: "UpdateBlog",
			Handler:    _BlogService_UpdateBlog_Handler,
		},
		{
			MethodName: "DeleteBlog",
			Handler:    _BlogService_DeleteBlog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBlogs",
			Handler:       _BlogService_ListBlogs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/blog.proto",
}

func init() { proto.RegisterFile("proto/blog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x0d, 0x15, 0xb1, 0x0c, 0x42, 0x74, 0xf4, 0xd0, 0xd4, 0xf8, 0x91, 0x9e, 0xf4, 0x20, 0x10,
	0x8c, 0xfe, 0x00, 0xf4, 0x62, 0xe2, 0xa9, 0xc6, 0x8b, 0x17, 0x03, 0xdd, 0x09, 0x6e, 0xd2, 0xb0,
	0xd0, 0x59, 0xfc, 0x39, 0xfe, 0x56, 0xb3, 0xbb, 0x59, 0xdb, 0x02, 0x09, 0x7a, 0xdb, 0x79, 0xf3,
	0x5e, 0xdf, 0xeb, 0xdb, 0x2c, 0x1c, 0x2d, 0x0a, 0xa5, 0xd5, 0x60, 0x9a, 0xab, 0x59, 0xdf, 0x1e,
	0xb1, 0x69, 0xce, 0x49, 0x06, 0xcd, 0x71, 0xae, 0x66, 0xd8, 0x83, 0x40, 0x8a, 0xa8, 0x71, 0xd5,
	0xb8, 0x6e, 0xa7, 0x81, 0x14, 0x78, 0x06, 0xed, 0xc9, 0x4a, 0x7f, 0xaa, 0xe2, 0x43, 0x8a, 0x28,
	0xb0, 0x70, 0xe8, 0x80, 0x67, 0x81, 0xa7, 0xb0, 0xaf, 0xa5, 0xce, 0x29, 0xda, 0xb3, 0x0b, 0x37,
	0x60, 0x04, 0x07, 0x99, 0x9a, 0x6b, 0x9a, 0xeb, 0xa8, 0x69, 0x71, 0x3f, 0x26, 0x03, 0xe8, 0x3e,
	0x16, 0x34, 0xd1, 0x64, 0xac, 0x52, 0x5a, 0xe2, 0x05, 0x58, 0x77, 0xeb, 0xd7, 0x19, 0x41, 0xdf,
	0xc6, 0xb2, 0x4b, 0x97, 0x6a, 0x4d, 0xc0, 0x3b, 0x05, 0xe7, 0xd0, 0x49, 0x69, 0x22, 0xfc, 0xf7,
	0xd7, 0xfe, 0x26, 0xb9, 0xad, 0xae, 0xf9, 0x2f, 0xf6, 0x6f, 0x0b, 0xf1, 0xbf, 0xbc, 0x55, 0xc1,
	0x6e, 0x87, 0x4b, 0xe8, 0x3e, 0x51, 0x4e, 0xa5, 0xc3, 0x7a, 0xe2, 0x9b, 0x3a, 0x81, 0x4d, 0xbb,
	0xbc, 0xca, 0x32, 0x62, 0xb6, 0xac, 0x30, 0xf5, 0x63, 0xd2, 0x83, 0xc3, 0x17, 0xc9, 0xda, 0x10,
	0x39, 0xa5, 0x65, 0xd2, 0xaf, 0xcd, 0x3b, 0xb3, 0x8c, 0xbe, 0x03, 0xe8, 0x98, 0xf1, 0x95, 0x8a,
	0x2f, 0x99, 0x11, 0x3e, 0x00, 0x94, 0xe5, 0xe3, 0x89, 0xe3, 0xd7, 0xee, 0x2f, 0xde, 0x02, 0x32,
	0x0e, 0x21, 0xf4, 0x25, 0xe3, 0xb1, 0x23, 0x54, 0xee, 0x24, 0xde, 0x80, 0xd8, 0x38, 0x95, 0xb5,
	0x79, 0xa7, 0x5a, 0xf3, 0xf1, 0x16, 0xd0, 0xea, 0xca, 0x72, 0xbc, 0xae, 0xd6, 0x67, 0xbc, 0x05,
	0x64, 0xbc, 0x87, 0xf6, 0x6f, 0x33, 0x88, 0x8e, 0x51, 0xad, 0x2e, 0xde, 0xc4, 0x78, 0xd8, 0x18,
	0x87, 0xef, 0x2d, 0x03, 0x2f, 0xa6, 0xd3, 0x96, 0x7d, 0x3a, 0x77, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xf7, 0x06, 0x52, 0x1a, 0x4e, 0x03, 0x00, 0x00,
}
